#ifndef __KSU_H_KSU_CORE
#define __KSU_H_KSU_CORE

#include <linux/init.h>
#include <vdso/bits.h>

#ifdef CONFIG_KSU_SUSFS
#define KSU_SUSFS_SUS_PATH_FLAG					BIT(0)
#define KSU_SUSFS_SUS_MOUNT_FLAG				BIT(1)
#define KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT_FLAG		BIT(2)
#define KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT_FLAG			BIT(3)
#define KSU_SUSFS_SUS_KSTAT_FLAG				BIT(4)
#define KSU_SUSFS_SUS_OVERLAYFS_FLAG				BIT(5)
#define KSU_SUSFS_TRY_UMOUNT_FLAG				BIT(6)
#define KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT_FLAG	BIT(7)
#define KSU_SUSFS_SPOOF_UNAME_FLAG				BIT(8)
#define KSU_SUSFS_ENABLE_LOG_FLAG				BIT(9)
#define KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS_FLAG			BIT(10)
#define KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG_FLAG		BIT(11)
#define KSU_SUSFS_OPEN_REDIRECT_FLAG				BIT(12)
#define KSU_SUSFS_SUS_SU_FLAG					BIT(13)
#define KSU_SUSFS_HAS_MAGIC_MOUNT_FLAG				BIT(14)
#endif

void __init ksu_core_init(void);
void ksu_core_exit(void);

#endif
